# Generated by Django 4.2.23 on 2025-08-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='package_images/')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(help_text='e.g., 4 Days / 3 Nights', max_length=50)),
                ('include_meals', models.BooleanField(default=False)),
                ('include_hotels', models.BooleanField(default=False)),
                ('include_flights', models.BooleanField(default=False)),
                ('include_sightseeing', models.BooleanField(default=False)),
                ('custom_includes', models.TextField(blank=True, help_text='Other things included')),
                ('short_itinerary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.category')),
            ],
        ),
    ]
